### ISSUE TITLE
setup grafana dash for spaces/providers/accounts

### ISSUE THREAD

**Issue by hugomrdias** [web3-storage/w3protocol#114]

**Comment by gobengo** [comment]
* define info access has that would be useful in a dashboard
  * e.g. new account creation counter
* expose that info to prometheus
* create dash in grafana

**Comment by hugomrdias** [comment]
Metrics in the workers are handled by Cloudflare Analytics Engine, our grafana already has it as an source. Its basically clickhouse.

example: https://daghouse.grafana.net/d/rLkgx_W4k/w3access-backend?orgId=1

**Comment by hugomrdias** [comment]
this is the only data point being written right now https://github.com/web3-storage/w3protocol/blob/21502882ad522e9a646703370ffaf6b5e3676a6b/packages/access-api/src/service/voucher-redeem.js#L30-L33

**Comment by gobengo** [comment]
https://github.com/web3-storage/w3infra/issues/169
