### ISSUE TITLE
Invalid UCAN chains seem to get authorized

### ISSUE THREAD

**Issue by Gozala** [web3-storage/w3protocol#179]
As per this long thread https://github.com/web3-storage/w3protocol/pull/148/files#r1024259741 we seem to have tests that create invalid UCAN chains, yet get somehow authorized instead of causing erros

https://github.com/web3-storage/w3protocol/blob/2923aceb7e5dfb1f12b42b8caf9c2f4416238650/packages/upload-client/test/index.test.js#L29-L42

**Comment by Gozala** [comment]
Looks like proofs are not even included in upload requests

https://github.com/web3-storage/w3protocol/blob/2923aceb7e5dfb1f12b42b8caf9c2f4416238650/packages/upload-client/src/upload.js#L33-L41

**Comment by alanshaw** [comment]
This was fixed :) https://github.com/web3-storage/w3protocol/blob/main/packages/upload-client/src/upload.js#L45
