### ISSUE TITLE
Use same did across access / upload API services

### ISSUE THREAD

**Issue by Gozala** [web3-storage/w3protocol#183]
I think having two different did's and endpoints clients need to interact with is incidental complexity we're pushing onto users, it seems that only reason we're dealing with this is because we run some code in CF and other in AWS, but perhaps we can hide that under the curtain ?

E.g. with ucanto forwarding delegations is fairly trivial, perhaps we should consider doing that ? In the future we could probably even remove need to run code on AWS.

I don't know what is best compromise here, but I do think we should not neglect this 

Parts
* https://github.com/web3-storage/w3protocol/issues/237
* https://github.com/web3-storage/upload-api/issues/63
* https://github.com/web3-storage/w3infra/issues/90

**Comment by gobengo** [comment]
Working toward milestone
* web3.storage platform DIDs
  * production: `did:web:web3.storage`
  * staging: `did:web:staging.web3.storage`
* access-api accepts invocations with aud=did:web:web3.storage
  * [ ] https://github.com/web3-storage/w3protocol/issues/237 
    * [x] https://github.com/web3-storage/w3protocol/pull/275
  * [ ] configure access-api staging to have env.DID=did:web:staging.web3.storage
  * [ ] configure access-api production to have env.DID=did:web:web3.storage
* upload-api accepts invocations with aud=did:web:web3.storage
  * [ ] PR so upload-api uses env.DID for ucanto server id, if present
  * [ ] configure upload-api staging to have env.DID set

Future (not now)
* unify the ucanto http service URLs so clients don't have to manage one per w3 service, but instead just one per w3 platform environment (usually only 1 when env=production)

**Comment by gobengo** [comment]
I think this is done
