### ISSUE TITLE
Remove side effect from access client agent delegations method

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/w3protocol#219]
Removing the expired delegations when fetching the list of delegations makes this method async and forces a whole bunch of other methods to be async that don't need to be. Please can we remove the side effect?

**Comment by hugomrdias** [comment]
which method ?

**Comment by alanshaw** [comment]
`#delegations()` - it deletes expired delegations it encounters and calls `await this.store.save(this.data)`.

It makes `delegations()`, `delegationsWithMeta()` and `proofs()` necessarily async when they don't need to be.

**Comment by hugomrdias** [comment]
any ideas how to clean up expired ucans ?

**Comment by alanshaw** [comment]
`.gc()`?

**Comment by hugomrdias** [comment]
but then you need to remember to always call that, and you are back to async function. I implemented it like this because most ttl/lru kv work like this on `get` or `list` do the clean up.
