### ISSUE TITLE
Handle archive format change in clients

### ISSUE THREAD

**Issue by Gozala** [web3-storage/w3protocol#236]
Recent changes https://github.com/web3-storage/ucanto/pull/149 in ucanto change an archive format. This has implications on the clients who will try to load signer from the previously stored archive in IndexedDB.

Previous structure was:

```ts
export type SignerArchive<Self extends Signer = Signer> =
  | ByteView<Self>
  | SignerInfo<Self>

export interface SignerInfo<Self extends Signer = Signer> {
  readonly did: ReturnType<Self['did']>
  readonly key: CryptoKey
}
```

New structure is:

```ts
/**
 * {@link Signer} keys and it's DID that can be used for persist and restore
 * signer across sessions.
 */
export interface SignerArchive<
  ID extends DID = DID,
  Alg extends SigAlg = SigAlg
> {
  /**
   * [DID Subject](https://www.w3.org/TR/did-core/#did-subject) for this
   * signer.
   */
  id: ID

  /**
   * Set of private keys this signer uses keyed by corresponding [did:key][].
   *
   * ⚠️ At the moment signers only support single key use case, however we may
   * change that in the future, which is why data model is forward designed to
   * support multiple keys.
   *
   * [did:key]:https://w3c-ccg.github.io/did-method-key/
   */
  keys: { [Key: DIDKey]: KeyArchive<Alg> }
}

/**
 * Represents a private key which will be in `CryptoKey` format if it is
 * non-extractable or is byte encoded when extractable.
 */
export type KeyArchive<Alg extends SigAlg = SigAlg> =
  | CryptoKey
  | ByteView<SignerKey<Alg> & CryptoKey>
```

If we ignore the possibility that keys may be in binary as opposed to `CryptoKey` upgrading old archive to new will boil down to:

```ts
const upgradeArchive = ({ did, key }) => ({ id: did, keys: {[did]:key} })
```

I think clients should probably add IndexDB migration thing to migrate all records to new format to avoid breakage

**Comment by Gozala** [comment]
@alanshaw the issue we discussed earlier in the call

**Comment by Gozala** [comment]
I could add `.fromLegacy(archive)` to the ucanto, but I think doing it inside the indexdb migration would be a better option

**Comment by alanshaw** [comment]
There's no code in production that uses this yet so it's safe to change.

**Comment by Gozala** [comment]
@alanshaw so should I just close this issue or do we want to still add something to the indexdb migration
