### ISSUE TITLE
access service & client should use `did:web:web3.storage`

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3protocol#237]
Motivation:
* towards https://github.com/web3-storage/w3protocol/issues/183
  * does the 'access' part

Parts
* [x] upgrade to @ucanto/{interface,principal} 4.0.0 which is required to use non-key DIDs https://github.com/web3-storage/w3protocol/pull/238
* [x] update access-api to create a ucanto server with a principal whose id is `did:{newServiceDid}`
  * https://github.com/web3-storage/w3protocol/pull/275
* [x] update access-client connection factory to use `did:{newServiceDid}` as default principal
  * or at least make the new well-known principal id/key values be easy to import so e.g. [w3ui doesn't have to hardcode them](https://github.com/web3-storage/w3ui/blob/dc2139f5e00c9195c480ce5c98a78b4296713ac7/packages/uploader-core/src/index.ts#L71)
* [ ] `test-ucanto-connection` dev tool in access-client cli to test the ucanto connection by sending an invocation to the expected id
* [ ] update cli `test-ucanto-connection` to send invocation to new access id (i.e. `did:{newServiceDid}`)

**Comment by hugomrdias** [comment]
is this the same https://github.com/web3-storage/w3protocol/issues/182 ? can we add this to the track issue ?

**Comment by gobengo** [comment]
@hugomrdias it's part of that, but just the part for access-client and access-api. that ticket is for 'all the services' afaict.

> can we add this to the track issue ?

sure idc. I put it in the equivalent milestone so it appears in the gh project board

**Comment by hugomrdias** [comment]
why did:web instead of did:dns ? @gobengo @Gozala

**Comment by gobengo** [comment]
> why did:web instead of did:dns ? @gobengo @Gozala

@hugomrdias only prior discussion [was here](https://github.com/web3-storage/specs/pull/12#discussion_r1033968381).

In short, it's because did:web is easier to implement and try things out with.
* implementable using only a web server, which access-api and upload-api already are
  * did:dns impl would beg question of how to manage the dns rules, which depends on how we operate our dns server and whether we outsource it e.g. to cloudflare or route53
* [`did:web` spec](https://github.com/w3c-ccg/did-method-web/) is maintained by members of w3c ccg, which is a group we can go to for advice while implementing. [`did:dns` spec](https://danubetech.github.io/did-method-dns/) maintained by one company atm (even though it's a rad company :P).
* This `did:dns` [TODO gives me pause](https://github.com/danubetech/did-method-dns/blob/main/index.html#L337)
* Most importantly, if `did:web` starts feeling like a bad choice, we can stop using it and try anything else.

**Comment by gobengo** [comment]
I think this is done now :) 
<img width="525" alt="Screenshot 2022-12-14 at 4 39 53 PM" src="https://user-images.githubusercontent.com/171782/207745410-5c9d7a57-9db9-4ec8-9716-af6af131f2e0.png">
