### ISSUE TITLE
Move validation websocket logic to a durable object

### ISSUE THREAD

**Issue by hugomrdias** [web3-storage/w3protocol#293]
The voucher validation and recover validation can take a long time with the current logic because it uses KV, websockets on workers and polls from the KVs until it finds the delegation to send back. 

Because KVs are eventually consistent it can take a bit to get the delegation into the KV responding to the websocket, if we move this to the durable object handling AWAKE device sync it will be instant.

Maybe we can even avoid storing delegations.

This would allow better feedback to the user because we have a direct connection to it and we can send errors.

**Comment by heyjay44** [comment]
PR here: https://github.com/web3-storage/w3protocol/pull/449
