### ISSUE TITLE
Implement `access/claim` in `access-api`

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/w3protocol#394]
https://github.com/web3-storage/specs/blob/feat/w3-authorization/w3-access.md#accessclaim

Tasks
* [x] https://github.com/web3-storage/w3protocol/issues/408
* [x] #393 - this is worth doing first as `access/claim` wont be useful for claiming anything until clients use `access/delegate` to write things that can be claimed [comment](https://github.com/web3-storage/w3protocol/issues/394#issuecomment-1412712124)
* [x] #455
* [x] #454
  * unblocks ["Access across multiple devices"](https://github.com/web3-storage/specs/blob/main/w3-access.md#access-across-multiple-devices)

**Comment by gobengo** [comment]
* [ ] define `access/claim` ability schema in `@web3-storage/capabilities`

**Comment by gobengo** [comment]
practically speaking, this can't be done until 

See [spec examples](https://github.com/web3-storage/specs/blob/main/w3-access.md#access-across-multiple-devices) for how `access/claim` is claiming delegations written by `access/delegate`.

So I added #393 as a subtask of this to reflect that dependency

**Comment by gobengo** [comment]
Remember to try to include this optimization
* https://github.com/web3-storage/w3protocol/pull/427#issuecomment-1442458085
* e.g. `DelegationsStorage` can have a method to query delegations out as car bytes but without parsing, that way we don't have to re-encode them to car bytes in the `access/claim` handler

**Comment by gobengo** [comment]
This is implemented in access-api main branch, and is depended on by `@web3-storage/access` as of https://github.com/web3-storage/w3protocol/issues/395
