### ISSUE TITLE
Succesfull access/authorize should delegate capabilities to the agent so it can claim them

### ISSUE THREAD

**Issue by Gozala** [web3-storage/w3protocol#457]
When user issues `access/authorize` with some agent it should send invocation like shown below which in English translates to: "Agent `did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi` is requesting all of the capabilities (`can: *`) to be delegated to it by `did:mailto:web.mail:alice` 

```json
{
  "v": "0.9.1",
  "iss": "did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi",
  "aud": "did:web:web3.storage",
  "att": [
    {
      "with": "did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi",
      "can": "access/authorize",
      "nb": {
        "iss": "did:mailto:web.mail:alice",
        "att": [{"can":"*"}]
       }
    }
  ],
  "prf": [],
  "exp": 1685602800,
  "s": {
    "/": {
      "bytes": "7aEDQJbJqmyMxTxcK05XQKWfvxG+Tv+LWCJeE18RSMnciCZ/RQ21U75LA0uFSvIjdqnF5RaauZTE8mh2ZYMBBejdJQ4"
    }
  }
}
```

Capability provider is expected to perform interactive authorization with an email holder using email flow. If and when user grants requested capabilities `access/authorize` provider is expected to delegate two capabilities to `did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi` (probably through `access/delegate` invocation)

1. Delegation from `did:mailto:web.mail:alice` to `did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi` that is [signed a special signature type](https://github.com/web3-storage/specs/blob/feat/auth%2Baccount/w3-account.md#authorization-session-signature-format) (that is basically not signed).

```json
{
  "v": "0.9.1",
  "iss": "did:mailto:web.mail:alice",
  "aud": "did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi",
  "att": [
    {
        "with": "ucan:*",
        "can": "*"
    }
  ],
  "prf": [],
  "exp": null,
  "s": {
    "/": {
      "bytes": "gKADAA"
    }
  }
}
```

2. Delegation from `did:web:web3.storage` to `did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi` that attests to the fact that first delegation ☝️ had been checked to be authorized by the user. This is attestation from us telling that hey don't check signature on the first one because we did checked it to be authorized.

```json
{
  "v": "0.9.1",
  "iss": "did:web:web3.storage",
  "aud": "did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi",
  "att": [
    {
      "with": "did:web:web3.storage",
      "can": "ucan/attest",
      "nb": {
          "proof": { "/": "bafy...above-delegation" }
       }
    }
  ],
  "prf": [],
  "exp": null,
  "s": {
    "/": {
      "bytes": "7aEDQJbJqmyMxTxcK05XQKWfvxG+Tv+LWCJeE18RSMnciCZ/RQ21U75LA0uFSvIjdqnF5RaauZTE8mh2ZYMBBejdJQ4"
    }
  }
}
```

All of the above implies that after user successfully  completed `access/authorize` with `did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi` agent, it can invoke `access/claim` from that agent and receive above two delegations because those were both delegated to it.

It also means that now `did:key:z6Mkk89bC3JrVqKie71YEcc5M1SMVxuCgNx6zLZ8SYJsxALi` can use above two delegations in the invocation proofs to do all the things that had been delegated to the `did:mailto:web.mail:alice`.

However there is one last piece to this puzzle, delegation from space did to account did must exist. Today we won't have such delegations because our clients have not been making them.

**Comment by gobengo** [comment]
[This PR implements](https://github.com/web3-storage/w3protocol/pull/460) the second delegation described above , but using can=./update instead of the WIP can=ucan/attest

**Comment by Gozala** [comment]
This is blocked on https://github.com/web3-storage/ucanto/pull/227 which has merged last night, but I do need to make a release

**Comment by Gozala** [comment]
This requires spec changes https://github.com/web3-storage/specs/pull/50 which are awaiting reviews
