### ISSUE TITLE
as a w3up user, I can visit the w3console web app, which is hosted on two separate domains (one for nft.storage and web3.storage)

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3protocol#488]
- [ ] Deploy two instances of w3console
- [ ] Point beta domains to deployed instances
- [ ] Add a `/terms` path to put in terms of service (unblocks https://github.com/web3-storage/w3ui/issues/397)
- [ ] Configure one instance to create NFT.Storage accounts (registering with them as the provider, etc.), the other web3.storage

**Comment by alanshaw** [comment]
https://github.com/web3-storage/w3ui/pull/402
