### ISSUE TITLE
as a w3up user, I know I should use the same email address as I did with nft.storage or web3.storage

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3protocol#490]

**Comment by dchoi27** [comment]
This user story should be taken care of by:
- [ ] https://github.com/web3-storage/w3cli/issues/54
- [ ] https://github.com/web3-storage/w3protocol/issues/532
- [ ] https://github.com/web3-storage/w3ui/issues/397
- [ ] https://github.com/web3-storage/w3up-client/issues/84

**Comment by dchoi27** [comment]
Closing this because we have individual tracking issues
