### ISSUE TITLE
update ToS for nft.storage and web3.storage

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3protocol#491]
Specifics [here](https://www.notion.so/w3up-in-March-2023-9dc6a4e0c3114a1589b350b403873b0f?pvs=4#628686d9a2ae48b6896f62c46a00df50)

**Comment by dchoi27** [comment]
- [] Finalize ToS language with Legal
- [] Post ToS to `/terms` on both web app domains

**Comment by dchoi27** [comment]
Closing this because we have individual tracking issues for the remaining items
