### ISSUE TITLE
MVP readme docs

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3protocol#493]

**Comment by dchoi27** [comment]
Is it ok OK if we close this one in favor of these?
- [ ] https://github.com/web3-storage/w3cli/issues/54
- [ ] https://github.com/web3-storage/w3up-client/issues/84
- [ ] https://github.com/web3-storage/w3ui/issues/398

**Comment by dchoi27** [comment]
or we can leave this issue open as a user story (as a new user, i should know how to...) though i personally don't need it to keep track
