### ISSUE TITLE
assert that `space/info` succeeds for spaces w/ storage provider registered via `provider/add` invocation

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3protocol#497]
Motivation:
* @Gozala asked me to
* it'll make it so that when w3infra invokes `space/info` as part of handling `store/add` that its not rejected

**Comment by Gozala** [comment]
Long term we should probably do https://github.com/web3-storage/w3protocol/issues/495, but for now this would unblock the store/* and upload/* with new account stuff.
