### ISSUE TITLE
change release-please manifest back to non-explicit version numbers

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3protocol#591]
Motivation:
* followup to https://github.com/web3-storage/w3protocol/pull/586

**Comment by travis** [comment]
once we have released these versions we need to un-pin: 
![](https://files.slack.com/files-pri/TEHTVS1L6-F050AQ92FL0/screenshot_2023-03-21_at_12.48.21_pm.png)

**Comment by travis** [comment]
it will be once https://github.com/web3-storage/w3protocol/pull/654 is merged!
