### ISSUE TITLE
Finalize moved store interfaces/capabilities, move sigv4 to use repo.

### ISSUE THREAD

**Issue by ice-breaker-tg** [web3-storage/w3protocol#65]
This should get us in position to also complete #54

**Comment by hugomrdias** [comment]
is this done yet ?

**Comment by JeffLowe** [comment]
Looks like the move to sigv4 in in PR https://github.com/web3-storage/w3up/pull/221

**Comment by hugomrdias** [comment]
can i close this ?

**Comment by JeffLowe** [comment]
Not yet.
