### ISSUE TITLE
Move capabilities into own package PLZ

### ISSUE THREAD

**Issue by Gozala** [web3-storage/w3protocol#80]
Hey @hugomrdias I would really like to decouple iterations on protocol from iterations on access SDK etc.. can we please just move all the capability definitions into own package e.g. `@web3-storage/protocol` or `@web3-storage/capabilities` and pull those in from wherever we need.

**Comment by hugomrdias** [comment]
we can for sure, do we need to do it now though ? i would like to avoid having everyone using capabilities directly we should have an abstraction like the Agent or something else so we can make changes in the caps and backend without bringing the world

**Comment by Gozala** [comment]
I think it makes sense to have a package with basically protocols, that is capabilities and some markdowns explaining the interaction.

Those could be the pulled in by the agent / client library that our tools and libraries can depend upon. Those also could be pulled in by various service implementations.

Current setup makes iteration on the protocol somewhat coupled with iteration on the implementation and I would like to be able to decouple them a bit more

**Comment by gobengo** [comment]
I'll do this next week. Accidentally created a duplicate. Copying this description from that:

Acceptance Criteria:
* w3protocol monorepo has a new package containing just the capability objects used in the protocols
* clients like access-client import the capabilities from the capabilities package

Ideas
* Should we also split up the capabilities by [service](https://github.com/web3-storage/w3protocol/blob/main/spec/services.md): e.g. accounts, storage, upload ?

**Comment by Gozala** [comment]
> Should we also split up the capabilities by [service](https://github.com/web3-storage/w3protocol/blob/main/spec/services.md): e.g. accounts, storage, upload ?

definitely split into separate modules, not sure separate packages are worth it, probably just going to only increase overhead right now

**Comment by gobengo** [comment]
Reminder to me:

* [ ] ensure docs for `@web3-storage/capabilities` appear here https://web3-storage.github.io/w3protocol/modules.html
* [ ] ensure CI releases to npm
  * [ ] ensure `npm install @web3-storage/capabilities` works once released

**Comment by gobengo** [comment]
@hugomrdias I'm assuming it's a good idea to release this to npm. I think that means I should add to this conditional to also run the release job for `packages/capabilities`? https://github.com/web3-storage/w3protocol/blob/191e2427529e113d67d5a6ec8ab7e7b4368b1c58/.github/workflows/release.yml#L40

**Comment by gobengo** [comment]
After merge
* [ ] ensure CI releases to npm

After release:
* [ ] ensure docs for `@web3-storage/capabilities` appear here https://web3-storage.github.io/w3protocol/modules.html

**Comment by gobengo** [comment]
```
bengo@bengo ~/tmp/test-caps ⚡  node
Welcome to Node.js v18.10.0.
Type ".help" for more information.
> (await import('@web3-storage/capabilities')).Voucher.claim.invoke({ with: 'did:key:foo', nb: { product: 'did:key:foo', identity: 'mailto:bengo@dag.house' } })
IssuedInvocation {
  issuer: undefined,
  audience: undefined,
  proofs: [],
  capabilities: [ { can: 'voucher/claim', with: 'did:key:foo', nb: [Object] } ],
  expiration: undefined,
  lifetimeInSeconds: undefined,
  notBefore: undefined,
  nonce: undefined,
  facts: []
}
```

**Comment by gobengo** [comment]
https://web3-storage.github.io/w3protocol/modules/_web3_storage_capabilities.html
