### ISSUE TITLE
feat: integrate upload/* protocol into w3up

### ISSUE THREAD

**Issue by Gozala** [web3-storage/w3protocol#82]
- [x] Land https://github.com/web3-storage/w3-protocol/pull/81
- [ ] Implementing a providers and deploying them on AWS
- [ ] Updating client / cli to use `upload/add` on uploads

**Comment by Gozala** [comment]
Let's try and have demo of this working

**Comment by Gozala** [comment]
Optionally do the paging

**Comment by Gozala** [comment]
@jchris @mikeal we need your input in regards to what `cli remove` should do, which is it either:

1. Removes entry from the upload list and does not do anything about `store` list (that is cars in the account).
2. Removes entry from the upload list and corresponding CARS from the store list.

I personally think it should just remove it from the upload list and maybe have a separate command or a flag to also remove corresponding cars from the store list. However removing cars from the store list can be bit tricky because technically multiple uploads can refer to the same CAR so we may have to remove some and leave the others.

**Comment by Gozala** [comment]
Linking to the https://github.com/web3-storage/w3up-cli/pull/119 here

**Comment by Gozala** [comment]
> @jchris @mikeal we need your input in regards to what `cli remove` should do, which is it either:
> 
>     1. Removes entry from the upload list and does not do anything about `store` list (that is cars in the account).
> 
>     2. Removes entry from the upload list and corresponding CARS from the store list.
> 
> 
> I personally think it should just remove it from the upload list and maybe have a separate command or a flag to also remove corresponding cars from the store list. However removing cars from the store list can be bit tricky because technically multiple uploads can refer to the same CAR so we may have to remove some and leave the others.

Thinking about this a bit more I think we should just not have `cli remove` and instead have:

1. `cli unlink upload_cid` that just removes item form the upload list.
2. `cli delete upload_cid` removes cid from both upload list and all linked cars not referenced by by other uploads  from the store list.


We should have whole another `cli store` command subgroup for listing / deleting CARs from the account store.

**Comment by ice-breaker-tg** [comment]
https://hackmd.io/@ice-breaker/w3up-interface
https://hackmd.io/@ice-breaker/w3up-cli-ux

(both are wip)

**Comment by Gozala** [comment]
So for me personally it makes sense to:

1. Have `cli store add/remove/list` commands that map directly to capabilities.
2. Have `cli upload add/remove/list` commands that map directly to capabilities.
3. Have `cli upload/delete` top level commands that may execute multiple capabilities e.g. delete doing both `upload/remove` and `store/remove`

Note that user may not have capabilities to delete CARS but have capabilities to remove uploads from list.

**Comment by hugomrdias** [comment]
are we doing this pre 0.9 ?

**Comment by Gozala** [comment]
Yeah plan was to get it out last week while you were all in nodeconf, but we did not managed to.

I think @ice-breaker-tg has it almost done & switching it over to 0.9 shouldn’t require much work so I think it’s best to finish and then just update caps to upgrade to 0.9

**Comment by JeffLowe** [comment]
This may be irrelevant since all this now lives in the new w3upload infra
